# Generated by Django 4.0.5 on 2022-06-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='population',
        ),
    ]
