# Generated by Django 4.0.5 on 2022-06-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0003_alter_population_admin_name_alter_population_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='lat',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
        migrations.AlterField(
            model_name='population',
            name='lng',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
        migrations.AlterField(
            model_name='population',
            name='population',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
        migrations.AlterField(
            model_name='population',
            name='population_proper',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
    ]
