# Generated by Django 4.0.5 on 2022-06-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0004_alter_population_lat_alter_population_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='capital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
